### ISSUE TITLE
Suggestions for building with 2.11?

### ISSUE THREAD

**Issue by elbamos** [ibm-et/spark-kernel#112]
First off, great job.  Compiles and works very well.

Do you have suggestions for getting it to compile with 2.11 though?  The akka.zeromq dependency has to get changed, after that though I start getting errors like:  

[info] Compiling 44 Scala sources to /home/aelberg/spark-kernel/protocol/target/scala-2.11/classes...
[error] /home/aelberg/spark-kernel/kernel-api/src/main/scala/com/ibm/spark/interpreter/ScalaInterpreter.scala:26: object SparkJLineCompletion is not a member of package org.apache.spark.repl
[error] import org.apache.spark.repl.{SparkJLineCompletion, SparkIMain}
[error]        ^
[error] /home/aelberg/spark-kernel/kernel-api/src/main/scala/com/ibm/spark/interpreter/ScalaInterpreter.scala:153: value forMSIL is not a member of scala.tools.nsc.Global
[error]     require(!sparkIMain.global.forMSIL) // Only support JavaPlatform
[error]                                ^
[error] /home/aelberg/spark-kernel/kernel-api/src/main/scala/com/ibm/spark/interpreter/ScalaInterpreter.scala:366: value isReportingErrors is not a member of scala.tools.nsc.interpreter.SparkIMain
[error]         if (sparkIMain.isReportingErrors)
[error]                        ^
[error] /home/aelberg/spark-kernel/kernel-api/src/main/scala/com/ibm/spark/interpreter/ScalaInterpreter.scala:340: type mismatch;
[error]  found   : Option[Any]
[error]  required: Option[AnyRef]

Which I find rather mysterious.

**Comment by rcsenkbeil** [comment]
At the moment, the Spark Kernel does not support Scala 2.11.

I'm not sure about the import problem with `SparkJLineCompletion`, but the other two are minor API differences in Spark/Scala REPLs between 2.10 and 2.11. What needs to be done is support cross-compiling using the specific 2.10 and 2.11 code for each case.

The `require(!sparkIMain.global.forMSIL) // Only support JavaPlatform` can be removed for 2.11.

The `sparkIMain.isReportingErrors` was a refactoring I did in Spark's 2.10 REPL API, but not in 2.11. It either needs to be echoed in 2.11 or we just use the old API that was previously exposed in 2.10 (before the refactoring). The old code was `sparkIMain.reporter.hasErrors`.

SparkJLineCompetion should still exist and be public in their project, but I haven't checked recently.

Using sbt 0.13.8 would also be nice since it provides the facility to compiling different code: https://github.com/sbt/sbt/pull/1799

There should not be anything blocking the kernel from 2.11 once these cross compilations are in place.

**Comment by m4dc4p** [comment]
@rcsenkbeil I spent a day trying to port the kernel to Scala 2.11. I solved everything except for one remaining issue. 

Spark 1.4, targeting Scala 2.10, uses the "classServerURI" property from SparkIMain.scala. That property no longer exists when targeting 2.11. It's sort of exposed in Main.scala (https://github.com/apache/spark/blob/branch-1.4/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala), but I can't reliably get to it. For example, just accessing the `classServer` val (https://github.com/apache/spark/blob/branch-1.4/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala#L36) leads to runtime errors due to missing dependencies. Going down the road of adding those dependencies leads to more errors.

Any suggestions for either getting that value another way?

**Comment by rcsenkbeil** [comment]
Well, with 2.11, you have to create the HttpServer instance yourself (like they do in the Main.scala file). Did you create one? Or are you saying that creating one via `new HttpServer(conf, outputDir, new SecurityManager(conf))` is the problem?

If you create one yourself, you should be able to access the URI and set it on the SparkConf instance the same way they do here: https://github.com/apache/spark/blob/branch-1.4/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala#L69

The `HttpServer` class ([link](https://github.com/apache/spark/blob/3c0156899dc1ec1f7dfe6d7c8af47fa6dc7d00bf/core/src/main/scala/org/apache/spark/HttpServer.scala)) that they instantiate is package-protected, which means that it would need to be created via reflection if done outside of the `org.apache.spark` namespace.

**Comment by InTheNow** [comment]
Hi All, 

At risk of being seen as "shouting" or "throwing stones", where are you guys at on this issue? It would be great to have a 2.11.X version.

Cheers
Alistair

**Comment by chipsenkbeil** [comment]
@InTheNow, it's a very reasonable question to ask, no shouting or throwing stones implied! :) @jodersky is taking a look at this presently. He should be able to give you an update on his progress. Also, we are currently in the process of moving our issues and source over to the new [Apache incubator location](http://toree.apache.org); so, a JIRA might be added for this in the near future.
